apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: only-allow-app
  namespace: wisecow
spec:
  selector:
    matchLabels:
      app: app

  file:
    action: block
  process:
    action: block

  allow:
    - process:
        path: /app
    - file:
        directory: /
        recursive: true
